INSERT INTO teams (group_id, team_name, flag, continente, capital, population, team_capitan, team_capitan_img)
VALUES
    (1, "Morocco", "./countries/morocco.png", "Africa", "RABAT", 37.08, "Hakim Ziyech", "./players/21.webp"),
    (1, "France", "./countries/france.png", "Europe", "Paris", 65273511.00, "Kylian Mbappe", "./players/13.webp"),
    (1, "Uruguay", "./countries/uruguay.png", "South America", "Montevideo", 3518552.00, "Luis Suarez", "./players/32.webp"),
    (1, "Korea", "./countries/korea.png", "Asia", "Seoul", 51269185.00, "Cho Gue-sung", "./players/30.webp"),
    (2, "Australia", "./countries/australia.png", "Oceania", "Canberra", 25499884.00, "Mathew Leckie", "./players/17.webp"),
    (2, "USA", "./countries/usa.png", "North America", "Washington, D.C.", 331002651.00, "Christian Pulisic", "./players/6.webp"),
    (2, "England", "./countries/england.png", "Europe", "London", 67530172.00, "Marcus Rashford", "./players/5.webp"),
    (2, "Wales", "./countries/wales.png", "Europe", "Cardiff", 3162943.00, "Gareth Bale", "./players/8.webp"),
    (3, "Argentina", "./countries/argentina.png", "South America", "Buenos Aires", 45195777.00, "Lionel Messi", "./players/9.webp"),
    (3, "Germany", "./countries/germany.png", "Europe", "Berlin", 83149300.00, "Niclas Fullkrug", "./players/19.webp"),
    (3, "Ghana", "./countries/ghana.png", "Africa", "Accra", 30280811.00, "Mohammed Kudus", "./players/31.webp"),
    (3, "Iran", "./countries/iran.png", "Asia", "Tehran", 84078135.00, "Abolfazl Jalali", "./players/7.webp"),
    (4, "Mexico", "./countries/mexico.png", "North America", "Mexico City", 126190788.00, "HENRY MARTIN", "./players/12.webp"),
    (4, "Portugal", "./countries/portugal.png", "Europe", "Lisbon", 10276617.00, "Cristiano Ronaldo", "./players/29.webp"),
    (4, "Spain", "./countries/spain.png", "Europe", "Madrid", 47076781.00, "Alvaro Morata", "./players/18.webp"),
    (4, "Brazil", "./countries/brazil.png", "South America", "Brasília", 212559417.00, "Richarlison", "./players/25.webp"),
    (5, "Cameroon", "./countries/cameroon.png", "Africa", "Yaoundé", 26545863.00, "Vincent Aboubakar", "./players/27.webp"),
    (5, "Canada", "./countries/canada.png", "North America", "Ottawa", 37742154.00, "Alphonso Davies", "./players/26.webp"),
    (5, "Croatia", "./countries/croatia.png", "Europe", "Zagreb", 4105267.00, "Luka Modrić", "./players/22.webp"),
    (5, "Denmark", "./countries/denmark.png", "Europe", "Copenhagen", 5792202.00, "Andreas Christensen", "./players/16.webp"),
    (6, "Belgium", "./countries/belgium.png", "Europe", "Brussels", 11589623.00, "Kevin De Bruyne", "./players/23.webp"),
    (6, "Japan", "./countries/japan.png", "Asia", "Tokyo", 126529100.00, "Ritsu DOAN", "./players/17.webp"),
    (6, "Netherlands", "./countries/netherlands.png", "Europe", "Amsterdam", 17134872.00, "Cody Gakpo", "./players/1.webp"),
    (6, "Costa Rica", "./countries/costarica.png", "North America", "San José", 5094118.00, "Yeltsin Tejeda", "./players/20.webp"),
    (7, "Saudi Arabia", "./countries/saudiarabia.png", "Asia", "Riyadh", 34813871.00, "Salem Al Dawsari", "./players/10.webp"),
    (7, "Senegal", "./countries/senegal.png", "Africa", "Dakar", 16743927.00, "Kalidou Koulibaly", "./players/2.webp"),
    (7, "Serbia", "./countries/serbia.png", "Europe", "Belgrade", 6963764.00, "Aleksandar Mitrovic", "./players/28.webp"),
    (7, "Poland", "./countries/poland.png", "Europe", "Warsaw", 38386000.00, "Robert Lewandowski", "./players/11.webp"),
    (8, "Tunisia", "./countries/tunisia.png", "Africa", "Tunis", 11818619.00, "Wahbi Khazri", "./players/15.webp"),
    (8, "Qatar", "./countries/qatar.png", "Asia", "Doha", 2881053.00, "Mohamed Muntari", "./players/3.webp"),
    (8, "Switzerland", "./countries/suitzeland.png", "Europe", "Bern", 8717321.00, "Breel Embolo", "./players/26.webp"),
    (8, "Ecuador", "./countries/ecuador.png", "South America", "Quito", 17643054.00, "Enner Valencia", "./players/4.webp");

    INSERT INTO staduims (group_id, staduim_name, staduim_img)

(1, "Mohammed V Stadium", "./staduims//mohammed_v_stadium.jpg"),
(2, "Grand Stade de Tanger", "./staduims//grand_stade_de_tanger.jpg"),
(3, "Estádio da Luz", "./staduims//estadio_da_luz.jpg"),
(4, "Estádio do Dragão", "./staduims//estadio_do_dragao.jpg"),
(5, "Camp Nou", "./staduims//camp_nou.jpg"),
(6, "Santiago Bernabéu", "./staduims//santiago_bernabeu.jpg"),
(7, "Wanda Metropolitano", "./staduims//wanda_metropolitano.jpg"),
(8, "Estadio Ramón Sánchez Pizjuán", "./staduims//estadio_ramon_sanchez_pizjuan.jpg");